-- what is the average selling price of the product?
select avg(SellingPrice)
from `e1.products`

select *
from `e1.products`

-- to name we use as

select avg(SellingPrice)as avg_selling_price
from `e1.products`
-- finance team wants the summary of all the payment transaction

select 
  count(*) as NUMBER_OF_PAYMENTS,
  sum(amount)as total_payment,
  min(amount)as min_payment,
  max(amount)as max_payment,
  avg(amount)as avg_payment
from `e1.payments`

-- give me the count of the number of the product within each category

select
  CategoryID,
  count(*)as prod_count
from `e1.products`
group by CategoryID

-- how many unit of each product has been sold
select *
from `e1.order_items`

select 
  ProductID,
  sum(Quantity) as pro_count
from `e1.order_items`
group by ProductID

-- what is the total values is generated by each product?

select *
from `e1.order_items`


select
  ProductID,
  sum(Total) as total_value
from `e1.order_items`
group by ProductID

-- what was the avg selling price at which each product was sold?
select
  ProductID,
  avg(SellingPrice) as avg_selling_price
from `e1.order_items`
group by ProductID

-- product sale summary

select *
from `e1.order_items`

select
  ProductID,
  count(*) as total_orders,
  sum(total) as total_sales,
  max(total) as max_sale,
  min(total) as min_sale,
  round(avg(total), 2) as avg_sale
from `e1.order_items`
group by ProductID


-- for each customer, how many orders are there for each of their different order status?
select *
from `e1.orders`

select
  CustomerID,
  Status,
  count(*) as order_status
from `e1.orders`
group by CustomerID,Status

select
  CustomerID,
  Status,
  count(*) as order_status
from `e1.orders`
group by Status,CustomerID











.



