-- for every warehouse, calculate:
-- WarehouseID -->warehouse
-- Warehouse name --> warehouse
-- Number of orders handled --> orders
-- Total quantity of products sold --> order_items
-- Total sales value --> order_items
-- -- importance -->warehouse table
-- Include warehouses even if they have no orders.
-- Display only warehouses where the total sales value is greater
-- than ₹2,00,000. -->having
-- Sort from highest to lowest total sales. --> order by

select *
from `e1.warehouses`
limit 5
select 
  w.warehouseID,
  w.Warehouse,
  count(distinct o.OrderID) as no_of_orders,
  coalesce(sum(oi.Total),0) as total_sales,
  coalesce(sum(oi.Quantity)) as total_qnty
from `e1.warehouses` as w
left join `e1.orders`as o
on w.warehouseID=o.WarehouseID
left join `e1.order_items` as oi
on o.OrderID=oi.OrderID
group by w.WarehouseID,w.Warehouse
having total_sales >200000
order by total_sales desc


alter table `e1.warehouses`
rename column string_field_0 to WarehouseID

alter table `e1.warehouses`
rename column string_field_1 to Warehouse


-- Calculate the total sales value generated by every customer.
-- Then display only those customers whose total spending is
-- greater than the average customer spending.
-- Display:
-- CustomerID --> customer
-- Customer name --> customer
-- Total spending --> order_items
-- Sort from highest spending to lowest.

select *
from `e1.order_items`
select *
from `e1.order_items`

select 
  c.CustomerID,
  c.Name,
  sum(oi.total)as total_sales
from `e1.customers` as c
inner join `e1.orders` as o
on c.CustomerID=o.CustomerID
inner join `e1.order_items` as oi
on o.OrderID=oi.OrderID
group by c.CustomerID,c.Name 
having total_sales>(
  select
   round(avg(total_sales),2)
  from (
    select
     o.customerID,
     sum(oi.total) as total_sales
    from `e1.order_items` as oi
    inner join `e1.orders`as o
    on oi.OrderID=o.OrderID
    group by o.CustomerID
  )
) 

-- Display only products whose total sales value is greater than
-- the average total sales value of products belonging to the same
-- category.
-- Display:
-- ProductID --> product
-- ProductName --> product
-- CategoryName --> category
-- TotalSales --> order_items
-- Sort by total sales from highest to lowest.
-- p1 -> s1
-- p2 -> s2
-- p3 -> s3

select
  p1.ProductID,
  sum(oi.Total) as total_sales
from `e1.products` as p1
inner join `e1.order_items` as oi
on p1.ProductID = oi.ProductID
where p1.CategoryID = p.CategoryID
group by p1.ProductID


-- case when statements
-- if-elseif-else
-- syntax:
case
when condition1 then result1
when condition2 then result2
when condition3 then result3
else default_result
end


-- categorise customers as
-- 18-20: genz,
-- 21-40 : adult,
-- 41 onwards : senior_citizen
select
  CustomerID,
  Age,
  Name,
  case 
    when Age >=18 and Age <= 20 then "GenZ"
    when Age >=21 and Age <= 40 then "Adult"
    when Age >=41 then "Senior_Citizen"
  end as age_group
from `e1.customers` as c


case
when condition1 then result1
when condition2 then result2
when condition3 then result3
else default_result
end


select 
  CustomerID,
  Name,
  Gender,
  case 
    when Gender ='M' then "Male"
    else "Female" 
  end as Gender_new
from e1.customers
-- For every order, calculate the total order value by adding the
-- Total column from order_items.
-- Then classify each order as:
-- High Value → Total order value ≥ ₹50,000
-- Medium Value → Total order value between ₹20,000 and ₹49,999
-- Low Value → Total order value < ₹20,000
-- Display:
-- OrderID --> orders
-- OrderDate --> orders
-- CustomerName --> customer
-- TotalOrderValue --> order_items
-- OrderCategory --> create using total_sales
-- Show the highest-value orders first. --> order by




